### ISSUE TITLE
Module no longer functions at all (1.0.7)

### ISSUE THREAD

**Issue by halfwalk** [ironmonk88/monks-little-details#10]
Using Foundry 0.7.9, dnd5e 1.2.4, hosted on The Forge

After installing the latest update (1.0.7), the module no longer has any function, and does not appear in the module settings, despite being activated in my modules list.

I've tried uninstalling entirely, and reinstalling fresh, to no avail.

![image](https://user-images.githubusercontent.com/68490032/107129482-9db07300-6893-11eb-850d-af65c6ac0106.png)

Checked with The Forge people and they said this:

![image](https://user-images.githubusercontent.com/68490032/107129685-1ebc3a00-6895-11eb-81b2-dd0d1c206c83.png)

**Comment by ironmonk88** [comment]
That was an issue when I was testing 1.0.7, but I swear it was fixed before release.
I rebuilt 1.0.7 and checked it, and the .js is there.
Can you try uninstalling and reinstalling and see if it works now?

**Comment by halfwalk** [comment]
Still no luck here.

I think if you rebuild but do not change the version number, it won't be properly scraped by the Bazaar (the Forge's module hosting system). So I believe until you change the version number again, it won't work out of the box for users of The Forge, because their server still has the non-working build.

However, if I download and manually install, the issue is resolved.

**Comment by ironmonk88** [comment]
Good to know.  1.0.8 has been released to hopefully solve the issue for the people on Forge.

**Comment by halfwalk** [comment]
This appears to have resolved the issue. I uninstalled, reinstalled from the Bazaar, and the module is working as it should now.

Thank you!

**Comment by ironmonk88** [comment]
Yayy.  Sorry about that weirdness.  Glad it's resolved.
