### ISSUE TITLE
[BUG] Right-clicking Actor Directory nav item in collapsed sidebar triggers last opened actor sheet

### ISSUE THREAD

**Issue by bemdesign-er** [ironmonk88/monks-little-details#208]
**Describe the bug**
When the sidebar is collapsed, right-clicking on the Actor nav item does not open up the Actors Directory popped out as expected but instead opens up the last opened actor's sheet.

**To Reproduce**
1. Collapse the sidebar
2. Right click on "Actors"
3. Instead of the Actors directory appearing popped out in a new window, the last opened actor's sheet opens up.

**Expected behavior**
The Actors directory should open up in a new window like the other nav items. It should not open up the sheet for the last viewed actor.

**Please complete as much of the following information as possible:**
 - Browser: Chrome Version 106.0.5249.103 
 - Foundry Version 10.287 and 10.288
 - System: DnD5e
 - Module version: 10.2
 - Are there any errors in the console: No errors but instead of rendering the Actor directory the console states, 'Rendering ActorSheet5eNPC'
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Yes. Issue only occurs with Little Details active.

**Additional context**
N/A

**Comment by Rokoki** [comment]
I have the same issue. Using most recent foundry version and mod version. Also it is only an issue when little details is active.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version

**Comment by this-gavagai** [comment]
Hello,

First off, thank you for these incredible modules. Common Display in particular has been key to my group adopting Foundry, and we love it.

Just a heads up, I'm still facing this issue on little details v10.6 (foundry v10.291). When the sidebar is in minimized mode, clicking on the "Actor" button brings up the last opened sheet. If I disable Little Details, the Actor Directory opens as expected.
